apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "empty-ns.fullname" . }}-config
  labels:
    {{- include "empty-ns.labels" . | nindent 4 }}
data:
  # Add your configuration key-value pairs here
  example-key: example-value