name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate tags
        shell: bash
        id: generate_tags
        run: ./generate-tag.sh
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          build-args: |
            APPVERSION=${{ steps.generate_tags.outputs.tag }}
          tags: mortbury.azurecr.io/empty-ns-controller:${{ steps.generate_tags.outputs.tag }}